version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: car-rental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: myat
      MYSQL_DATABASE: mzp_car_rental
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: .
    container_name: car-rental-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mzp_car_rental
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: myat
    ports:
      - "8080:8000"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
